---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: python
    tag: 3.8-slim-buster

inputs:
  - name: bpm-store-attachment
  - name: role

outputs:
  - name: generated
  
run:
  path: bpm-store-attachment/ci/tasks/bpm-store-attachment.sh