# COMMON ========================================

aws_secret_access_key: &aws_secret_access_key ((prices.service_account_access_key_secret))
aws_access_key_id: &aws_access_key_id ((prices.service_account_access_key_id))

aws_params: &aws_params
  AWS_ACCESS_KEY_ID: *aws_access_key_id
  AWS_SECRET_ACCESS_KEY: *aws_secret_access_key
  AWS_REGION: ((aws_region))
  AWS_SERVICE_ROLE: arn:aws:iam::((prices.account_((environment)))):role/prices-svc-deploy-attachment-lambda
  S3_NAME: ((environment)).((prices.tf_state_s3))
  S3_KEY: store-attachment/lambda.tfstate

tf_params: &tf_params
  <<: *aws_params
  WORKSPACE: ((workspace))
  TERRAFORM_SOURCE: bpm-store-attachment/terraform
  TF_VAR_stage: ((stage))

github_pull_creds: &github_pull_creds
  username: ((github.access_token))
  password: x-oauth-basic

# COMMON TASKS ==================================

authenticate: &authenticate
  task: authenticate
  file: bpm-ci-git/tasks/authenticate/task.yml
  params:
    <<: *aws_params

# RESOURCES =====================================
resource_types:
- name: pull-request
  type: docker-image
  source:
    repository: teliaoss/github-pr-resource

resources:
  - name: bpm-store-attachment
    type: pull-request
    check_every: 5m
    source:
      repository: ONSdigital/bpm-store-attachment
      access_token: ((github.access_token))

  - name: bpm-ci-git
    type: git
    icon: github-circle
    source:
      uri: https://github.com/ONSdigital/bpm-ci.git
      <<: *github_pull_creds

# JOBS ==========================================

jobs:
  - name: build
    plan:
      - in_parallel:
          - get: bpm-store-attachment
            trigger: true
          - get: bpm-ci-git
      - do:
          - *authenticate
          - task: generate
            file: bpm-store-attachment/ci/tasks/bpm-store-attachment.yml
          - task: terraform-apply
            file: bpm-store-attachment/ci/tasks/terraform_apply.yml
            params:
              <<: *tf_params

  - name: destroy
    plan:
      - in_parallel:
          - get: bpm-store-attachment
            passed: [build]
          - get: bpm-ci-git
      - do:
          - *authenticate
          - task: terraform-destroy
            file: bpm-store-attachment/ci/tasks/terraform_destroy.yml
            params:
              <<: *tf_params
